# Generated by Django 2.2 on 2019-04-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=8)),
                ('mal_id', models.IntegerField(unique=True)),
                ('url', models.URLField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('episodes', models.IntegerField()),
                ('image_url', models.URLField()),
                ('members', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('score', models.FloatField()),
            ],
        ),
    ]
